# Generated by Django 4.1.6 on 2023-03-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresults',
            name='user',
            field=models.CharField(default='lemosbc', max_length=100),
            preserve_default=False,
        ),
    ]
